### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by Deozaan** [HoneyHazard/balloonwar#1]
Hello,

I noticed that you've committed the source code for cInput to your public project. You may not have noticed the following details found in cInput.cs:

> This script is NOT free[...] Therefore the use of this script is strictly personal and may not be spread without permission.

Will you please remove cInput (and all related, non-free, 3rd-party materials) from any repositories you have (including their history) or make the repositories private?

Thanks!

**Comment by HoneyHazard** [comment]
I deleted the cInput files in this commit. https://github.com/HoneyHazard/balloonwar/commit/15b5604cfb0e1f971e5ece532293fd9227d6c879 Thank you and my apologies for uninentionally violating the license

**Comment by Deozaan** [comment]
Thanks! I appreciate your response.

That's a good start, but not a total solution. Anyone can browse this repository's history and see the cInput source files when they were in the project. Even the diff for commit 15b5604 has the source, showing the code that was removed.

In order to truly comply with the license, you'll need to edit the entire history of the repository to remove all traces of cInput throughout every revision it existed in, or else make the repository private so it can't be accessed by the public.

FYI, if being unable or unwilling to pay for a GitHub subscription is keeping you from being able to make this repository private, [BitBucket](http://bitbucket.com/) offers unlimited, free, private repositories.

**Comment by HoneyHazard** [comment]
So I've made this repo in hopes that two things could happen 1) someone is curious about the game scripts and file structure and can check them out and/or 2) someone clones the repo and builds the game and has some fun experimenting etc. 2) is ruled out completely because of cInput license. And because of 1) there is no point in me making this repo private. So the repo has to be public. This leaves me with option a) fiddle with git for half a day to collapse all commits into a single one so no traces of cInput are present b) delete the repo and start a new repo with no traces of cInput in it ever c) delete the repo and don't bother. I'm probably going with b) or c), so this repo is about to die. Wether or not it comes back as a public repo, it will have no cInput in it.
